#!/bin/bash
JARS=./jar/dcpssaj5.jar:./jar/builtin-typelib_2.10-4.1.1-SNAPSHOT.jar:./jar/dython-types-ospl_2.11-0.1.0.jar

#JYTHONPATH=/Users/kydos/xlab/jython/dython/dds

jython -J-Ddds.runtime=ospl -J-cp $JARS $*
