package dython.bit;

/**
* dython/bit/DythonHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/dython.idl
* Sunday, April 26, 2015 12:25:18 AM CEST
*/

public final class DythonHolder implements org.omg.CORBA.portable.Streamable
{
  public dython.bit.Dython value = null;

  public DythonHolder ()
  {
  }

  public DythonHolder (dython.bit.Dython initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dython.bit.DythonHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dython.bit.DythonHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dython.bit.DythonHelper.type ();
  }

}
