package dython.bit;


/**
* dython/bit/Dython.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/dython.idl
* Sunday, April 26, 2015 12:25:18 AM CEST
*/

/**
* Updated by idl2j
* from ../idl/dython.idl
* Sunday, April 26, 2015 12:25:19 AM CEST
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "Dython",
    keys = {}
)
public final class Dython implements org.omg.CORBA.portable.IDLEntity
{
  public String value = null;

  public Dython ()
  {
  } // ctor

  public Dython (String _value)
  {
    value = _value;
  } // ctor

} // class Dython
