package dython.bit;

/**
* dython/bit/KDythonHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/dython.idl
* Sunday, April 26, 2015 12:25:18 AM CEST
*/

public final class KDythonHolder implements org.omg.CORBA.portable.Streamable
{
  public dython.bit.KDython value = null;

  public KDythonHolder ()
  {
  }

  public KDythonHolder (dython.bit.KDython initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dython.bit.KDythonHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dython.bit.KDythonHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dython.bit.KDythonHelper.type ();
  }

}
